<?php

namespace AD\GsbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Nomdel'entityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlexisRepository extends EntityRepository
{
    public function laFonction(){
        $liste=$this->findAll();
        return $liste;
    }
}
